CREATE TABLE CARRO (
	ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	MARCA VARCHAR(100) NOT NULL,
	COR VARCHAR(100) NOT NULL,
	ANO VARCHAR(4) NOT NULL,
	VALOR DECIMAL(9,2) NOT NULL
)


